export { WAClient, DisconnectReason } from './socket/client.js'
export type { SocketConfig, ConnectionUpdate, Logger, IncomingMessage } from './socket/client.js'
export { NoiseHandler, NOISE_MODE, NOISE_WA_HEADER } from './socket/noise-handler.js'
export { Curve, generateSignalPubKey, signedKeyPair, hkdf, sha256, md5 } from './crypto/index.js'
export { hasNativeCrypto } from './crypto/native.js'
export type { KeyPair, SignedKeyPair } from './crypto/index.js'
export { initAuthState, initAuthCreds, makeInMemoryKeyStore } from './utils/auth-utils.js'
export type { AuthenticationState, AuthenticationCreds, SignalKeyStore } from './utils/auth-utils.js'
export { Browsers } from './utils/browser-utils.js'
export type { BrowserDescription } from './utils/browser-utils.js'
export { encodeBinaryNode, decodeBinaryNode } from './wabinary/index.js'
export type { BinaryNode } from './wabinary/types.js'
export { encodeMessage, decodeMessage } from './proto/message.js'
export type { IMessage, MediaMessage, ContextInfo } from './proto/message.js'
export { encryptMedia, decryptMedia, getMediaKeys, MEDIA_PATH_MAP } from './media/index.js'
export type { MediaType, MediaConnInfo } from './media/index.js'
export { SignalRepository } from './signal/repository.js'
export { buildUSyncDeviceQuery, parseUSyncDeviceResult, extractDeviceJids, deviceJid } from './usync/index.js'
